[package]
name = "convevo"
version = "0.5.2"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
# cargo build --release && strip ./target/release/convevo.exe

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }

# will be switched to origin `serde_merge` after pull request merged
serde_merge = { git = "https://github.com/convevo/serde_merge.git" }

# modified version of `shared_child`
shared_child = { git = "https://github.com/convevo/shared_child.rs.git" }

# anyhow = "1.0.44"

# [dependencies.cursive]
# version = "0.16.3"
# default-features = false
# features = ["crossterm-backend"]
