[package]
name = "convevo"
version = "0.6.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
# cargo build --release && strip ./target/release/convevo.exe

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
serde_merge = "0.1.3"
shared_child = "1.0.0"
cursive.version = "0.16.3"
cursive.default-features = false
cursive.features = ["crossterm-backend"]
