[package]
name = "convevo"
version = "0.5.4"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
# cargo build --release && strip ./target/release/convevo.exe

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
serde_merge = "0.1.3"

# modified version of `shared_child`
shared_child = { git = "https://github.com/convevo/shared_child.rs.git" }

cursive.version = "0.16.3"
cursive.default-features = false
cursive.features = ["crossterm-backend"]

# anyhow = "1.0.44"
