[package]
name = "convevo"
description = "Extensible file converter."
version = "0.6.2"
edition = "2021"
license = "MIT"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
# strip = true
# cargo build --release && strip ./target/release/convevo.exe

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
serde_merge = "0.1.3"
shared_child = "1.0.0"
yansi = "0.5.0"
