[package]
name = "foundry"
version = "0.3.0"
authors = ["kkocdko <kkocdko@163.com>"]
description = "Automatically generate and execute commands from templates."
edition = "2018"
repository = "https://github.com/kkocdko/foundry"
license = "Unlicense"

[profile.release]
panic = "abort"
lto = "fat"
# codegen-units = 1

[dependencies]
shared_child = "0.3.4"
os_pipe = "0.9.2"
toml = "0.5.6"
rust-embed = "5.6.0"
