[package]
name = "foundry"
version = "0.0.1"
authors = ["kkocdko <kkocdko@163.com>"]
description = "Generate and execute commands automatically by templates."
edition = "2018"
license = "Unlicense"

[dependencies]
toml = "0.5.5"

[profile.release]
panic = "abort"
