[package]
name = "cmdfactory"
version = "0.4.5"
edition = "2018"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
# strip cmdfactory.exe

[dependencies]
toml = "0.5.8"
# anyhow = "1.0.38"

[target."cfg(not(windows))".dependencies.libc]
version = "0.2.99"
