[package]
name = "foundry"
version = "0.1.4"
authors = ["kkocdko <kkocdko@163.com>"]
description = "Automatically generate and execute commands from templates."
edition = "2018"
repository = "https://github.com/kkocdko/foundry"
license = "Unlicense"

[profile.release]
panic = "abort"
lto = true

[dependencies]
toml = "0.5.6"
shared_child = "0.3.4"
