[package]
name = "foundry"
version = "0.1.2"
authors = ["kkocdko <kkocdko@163.com>"]
description = "Automatically generate and execute commands from templates."
edition = "2018"
license = "Unlicense"

[profile.release]
panic = "abort"
lto = true

[dependencies]
toml = "0.5.6"
