name: asset_ffmpeg
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        run: |
          curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz | tar -xJ --strip-components 1
          mv bin/ffmpeg ffmpeg
          zip -9 linux-x64.zip ffmpeg
      - name: Verify
        run: |
          uname -a
          ldd --version
          ldd ffmpeg || true
          ./ffmpeg -version
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_ffmpeg_20240929_' }}${{ github.run_id }}"
          files: linux-x64.zip
  mac-arm64:
    runs-on: macos-14
    steps:
      - name: Build
        run: |
          curl -O -L https://www.osxexperts.net/ffmpeg7arm.zip
          unzip ffmpeg7arm.zip
          [ $(sha256sum ffmpeg | cut -d' ' -f1) = "326895b16940f238d76e902fc71150f10c388c281985756f9850ff800a2f1499" ] && echo matched # 20240410 # unzip -l ffmpeg7arm.zip
          zip -9 mac-arm64.zip ffmpeg
      - name: Verify
        run: |
          uname -a
          otool -L ffmpeg || true
          ./ffmpeg -version
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_ffmpeg_20240929_' }}${{ github.run_id }}"
          files: mac-arm64.zip
  win-x64:
    runs-on: windows-2022
    steps:
      - name: Build
        shell: C:\msys64\msys2_shell.cmd -clang64 -defterm -here -no-start -e {0}
        run: |
          pacman -S --noconfirm zip unzip
          curl -O -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          unzip ffmpeg-master-latest-win64-gpl.zip
          mv ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe ffmpeg.exe
          zip -9 win-x64.zip ffmpeg.exe
      - name: Verify
        shell: C:\msys64\msys2_shell.cmd -clang64 -defterm -here -no-start -e {0}
        run: |
          uname -a
          ldd ffmpeg.exe || true
          ./ffmpeg.exe -version
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_ffmpeg_20240929_' }}${{ github.run_id }}"
          files: win-x64.zip
