name: asset_rsync
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        shell: sudo bash -e {0}
        run: |
          apt update
          apt install -y make gawk autoconf automake acl attr zlib1g-dev libattr1-dev libzstd-dev
          curl -L https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.2.tar.gz | tar -zx
          make -C xxHash-0.8.2 CC="musl-gcc -O3 -static" -j$(nproc)
          curl -L https://github.com/microsoft/mimalloc/archive/refs/tags/v2.1.4.tar.gz | tar -zx
          musl-gcc -c mimalloc-2.1.4/src/static.c -I mimalloc-2.1.4/include -o mimalloc.o -O2
          curl -L https://github.com/RsyncProject/rsync/archive/refs/tags/v3.3.0.tar.gz | tar -zx --strip-components 1
          cp -R -n /usr/include/zstd.h /usr/include/x86_64-linux-musl/
          cp -R -n /usr/lib/x86_64-linux-gnu/libzstd.a /usr/lib/x86_64-linux-musl/
          export CC="musl-gcc -O2 -static -I ./popt -I xxHash-0.8.2 -L xxHash-0.8.2 mimalloc.o"
          ./configure CC="$CC" --disable-lz4 --disable-openssl --disable-md2man --disable-debug
          make CC="$CC" -j$(nproc)
          strip rsync
          zip -9 linux-x64.zip rsync
      - name: Verify
        run: |
          uname -a
          ldd ./rsync || true
          ./rsync -V
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          prerelease: true
          tag_name: "${{ 'asset_rsync_3.3.0_' }}${{ github.run_id }}"
          files: linux-x64.zip
  win-x64:
    runs-on: windows-2022
    steps:
      - name: Build
        shell: C:\msys64\msys2_shell.cmd -defterm -here -no-start -e {0}
        run: |
          pacman -S --noconfirm libzstd-devel libxxhash-devel gcc zip autotools automake make
          curl -L https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.2.tar.gz | tar -zx
          make -C xxHash-0.8.2 CC="gcc -O3 -static" -j$(nproc)
          mv xxHash-0.8.2/libxxhash.a /usr/lib/
          curl -L https://github.com/RsyncProject/rsync/archive/refs/tags/v3.3.0.tar.gz | tar -zx --strip-components 1 --exclude "*.test"
          ./configure --disable-lz4 --disable-openssl --disable-md2man --disable-debug
          make CC="gcc -static -O2" -j$(nproc) || true # no -flto
          strip rsync.exe
          cp /usr/bin/msys-2.0.dll ./
          zip -9 win-x64.zip rsync.exe msys-2.0.dll
      - name: Verify
        run: |
          uname -a
          ldd ./rsync.exe || true
          ./rsync.exe -V
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          prerelease: true
          tag_name: "${{ 'asset_rsync_3.3.0_' }}${{ github.run_id }}"
          files: win-x64.zip
