name: asset_ngmddocs
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  any:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          curl -L https://github.com/angular/material.angular.io/archive/refs/heads/main.tar.gz | tar -zx --strip-components 1
          yarn install --immutable
          yarn prod-build
          zip -r -9 dist.zip dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_ngmddocs_20241006_' }}${{ github.run_id }}" # 19.0.0-next.2
          files: dist.zip
# Angular's material design 3 as the sample for us.
# For users, it has most of the features.
# For developers, it's huge and complex. So we just use it as ui sample.
