name: asset_busybox
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        run: |
          curl -o busybox.tar.zst -L https://mirror.pkgbuild.com/extra/os/x86_64/busybox-1.36.1-2-x86_64.pkg.tar.zst
          tar -xf busybox.tar.zst
          mv usr/bin/busybox busybox
          zip -9 linux-x64.zip busybox
      - name: Verify
        run: |
          uname -a
          ldd --version
          ldd busybox || true
          ./busybox
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_busybox_20241008_' }}${{ github.run_id }}"
          files: linux-x64.zip
  linux-arm64:
    runs-on: warp-ubuntu-2204-arm64-2x
    steps:
      - name: Build
        run: |
          curl -o busybox.tar.xz -L http://mirror.archlinuxarm.org/aarch64/extra/busybox-1.36.1-2-aarch64.pkg.tar.xz
          tar -xf busybox.tar.xz
          mv usr/bin/busybox busybox
          zip -9 linux-arm64.zip busybox
      - name: Verify
        run: |
          uname -a
          ldd --version
          ldd busybox || true
          ./busybox
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_busybox_20241008_' }}${{ github.run_id }}"
          files: linux-arm64.zip
  mac-arm64:
    runs-on: macos-14
    steps:
      - name: Build
        run: |
          curl -o busybox -L https://github.com/kernelzeroday/busybox-macos-arm64/releases/download/v1.20.0.git/busybox_unstripped
          chmod +x busybox
          zip -9 mac-arm64.zip busybox
      - name: Verify
        run: |
          uname -a
          otool -L busybox || true
          ./busybox
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_busybox_20241008_' }}${{ github.run_id }}" # 1.20.0 , it's so old, but works
          files: mac-arm64.zip
  win-x64:
    runs-on: windows-2022
    steps:
      - name: Build
        shell: C:\msys64\msys2_shell.cmd -clang64 -defterm -here -no-start -e {0}
        run: |
          pacman -S --noconfirm zip
          curl -o busybox.exe -L https://frippery.org/files/busybox/busybox-w64-FRP-5467-g9376eebd8.exe
          zip -9 win-x64.zip busybox.exe
      - name: Verify
        shell: C:\msys64\msys2_shell.cmd -clang64 -defterm -here -no-start -e {0}
        run: |
          uname -a
          ldd busybox.exe || true
          ./busybox.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_busybox_20241008_' }}${{ github.run_id }}" # acturally, it's based on 1.37 master
          files: win-x64.zip
  win-arm64:
    runs-on: windows-2022
    steps:
      - name: Build
        shell: C:\msys64\msys2_shell.cmd -clang64 -defterm -here -no-start -e {0}
        run: |
          pacman -S --noconfirm zip
          curl -o busybox.exe -L https://frippery.org/files/busybox/busybox-w64a-FRP-5467-g9376eebd8.exe
          zip -9 win-arm64.zip busybox.exe
      - name: Verify
        shell: C:\msys64\msys2_shell.cmd -clang64 -defterm -here -no-start -e {0}
        run: |
          uname -a
          # ldd busybox.exe || true # unable to test
          # ./busybox.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_busybox_20241008_' }}${{ github.run_id }}" # acturally, it's based on 1.37 master
          files: win-arm64.zip
# just download from other sources, version number is current date, may have different busybox version, see above to find the real version
