name: asset_drawstamputils
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  all:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        run: |
          echo "Thanks to xxss0903, below is Apache-2.0 licensed"
          curl -o drawstamputils.tar.gz -L https://github.com/xxss0903/drawstamputils/archive/347e2a2d617591d735de4813b4608b09c4e27583.tar.gz # 20241119 without warning dialogs
          curl -o extractstamp.tar.gz -L https://github.com/xxss0903/extractstamp/archive/c630526a9458038d6d322faa52b901a8bfde2f60.tar.gz # 20241026 without some function removal
          if [ $(sha1sum drawstamputils.tar.gz | cut -d" " -f1) != 67cf45689eae81c2c54dddec7ef0e11932360be8 ]; then exit 1; fi
          if [ $(sha1sum extractstamp.tar.gz | cut -d" " -f1) != 1e5d1f2a2ca8d1cc10b77722483dd9570b1e981b ]; then exit 1; fi
          tar -xf drawstamputils.tar.gz --strip-components=1
          npm install
          npm run build
          mv dist/assets/* dist/
          sed -i.bak 's|./assets/|./|g' dist/index.html
          tar -xf extractstamp.tar.gz --strip-components=1
          sed -i.bak 's|https://docs.opencv.org/4.x/opencv.js|https://registry.npmmirror.com/@techstark/opencv-js/v4.10.0-release.1/files/dist/opencv.js|' index.html
          mv index.html dist/extractstamp.html
          mv extractstamp.js dist/extractstamp.js
          rm -rf dist/*.png dist/*.svg dist/*.bak dist/assets
          zip -9 all.zip dist/*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: "`github.workflow_sha = ${{ github.workflow_sha }}`"
          tag_name: "${{ 'asset_drawstamputils_20241119_' }}${{ github.run_id }}"
          files: all.zip
