name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: Show toolchain info
        run: rustup toolchain list && rustup target list --installed 

      - name: Run cargo build
        run: cargo build # --release && strip ./target/release/cmdfactory

      - name: Run cargo test
        run: cargo test --verbose

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build-${{ matrix.os }}
      #     path: target/release/cmdfactory
