name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: Show Toolchain Info
        run: rustup toolchain list && rustup target list --installed

      - name: Test
        run: cargo test

      # - name: Build
      #   run: cargo build --release

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build-${{ matrix.os }}
      #     path: target/release/clevert*
