name: ci
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Do Nothing
        shell: sudo bash -e {0}
        run: |
          echo 1
