name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: List installed targets
        run: rustup target list --installed

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        # run: cargo build --release && strip ./target/release/cmdfactory
        run: cargo build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-release-${{ matrix.os }}
          path: target/release/cmdfactory
